---
title: "Day2_EDS221"
format: html
editor: visual
execute: 
  warning: false
---

## Making and indexing data in R

### Vectors

Making Vectors

```{r}
# make a vector using concatanate
dogs <- c("teddy", "khora", "waffle", "banjo", "tallie")
# check class of dogs
typeof(dogs)
class(dogs)

```

```{r}
# a vector can only have 1 type of data so it will combine to the largest common data type
my_breakfast <- c("waffles", 2, TRUE, "coffee")

typeof(my_breakfast)
```

```{r}
weights <- c(50, 60, 25, 35, 55)
# values are stored as doubles
typeof(weights)
# overarching categary my differ from how values are stored double is in a category of numeric
class(weights)
```

```{r}
weights_integer <- c(50L, 60L, 25L, 35L, 55L)

typeof(weights_integer)
```

```{r}
# asking a question about variable class aka is weights_integer a numeric
is.numeric(weights_integer)
```

```{r}
zipcodes <- c(93105, 93514, 93101, 93401)

class(zipcodes)
# use as. family of functions to recast data classes
zipcodes_character <- as.character(zipcodes)
```

### Create a vector with named elements

```{r}
# each of these things is an element, and the "" is the value of the element
dog_food <- c(teddy = "purina", khora ="alpo", waffle = "fancyfeast", banjo = "blue diamond", tallie = "farmer's dog")
# we assigned an order but did not change the vector that we are saving
test <- c(cat = 4, dog = 10, elephant = 11)
class(test)
```

```{r}
# return the value of the 2nd vector
dog_food[2]
# R uses 1-index
#Python and javascript uses 0-indexing
#another way to call a named vector
dog_food["khora"]
```

### Access ranges of values in a vector

Use: to refer to a range (low : high)

```{r}
trees <- c("ponderosa", "lodgepole", "jeffrey", "sugar", "bristlecone")
# what is the vector at position 3
trees[3]
# what are the vectors at position 3, 4, 5
trees[3:5]
```

### Warm-up for for loops

```{r}
# making an indexing helper
i <- 3
# returns trees 4th position vector
trees[i]
```

```{r}
# same thing as seq from = 1, to = 3
i <- seq(1:3)
# call back the sequence of i which is from = 1, to = 3
trees[i]
```

```{r}
# re-assigned position 3 so it is no longer "jeffrey"
trees[3] <- "oak"
trees
```

### Matrix Indexing

```{r}
fish_size <- matrix(c(0.8, 1.2, 0.4, 0.9), ncol = 2, nrow = 2, byrow = FALSE)

fish_size

class(fish_size)
# what is the structure of this
str(fish_size)
# within data structure type of values
typeof(fish_size)

#value of row 2 column 2
fish_size[2,2]
# value of all of column 2
fish_size[,2]
```

An edit to test branches

## Lists

```{r}
# use list() function to make a list
urchins <- list("blue", c(1, 2, 3), c("lunch", "dinner", "dessert"), 5L)
# show the list urchins
urchins
```

```{r}
# if you use single brackets it returns the element but maintains its data structure
urchins_list <- urchins[2]

# just return a vector
urchins_vector <- urchins[[2]]

class(urchins_list)
class(urchins_vector)
```

```{r}
# use list() function to make a list and name each value
urchins_named <- list(color = "blue", values = c(1, 2, 3), meal = c("lunch", "dinner", "dessert"), cost = 5L)
# show the list urchins
urchins_named
```

## Why do we name things?

```{r}
# this p-value means that there is a 1.15% chance that the two samples were drawn from populations with the same mean
sample1 <- c(1,2,3,4,5,3,2,4,1)
sample2 <- c(3,4,1,6,7,4,8,6,10,11)
# run a ttest
ttest_example <- t.test(sample1, sample2)
# show me the ttest
ttest_example
# what is this... it is a hypothesis test
class(ttest_example)
# how to find the p-value by using the name of the list within the hypothesis test
ttest_example$p.value
# mean size for trees in site a is greater than the mean size in site b (....my statistical summary, `r ttest_example$p.value`)
```
